spring.datasource.url=jdbc:postgresql://postgresql:5432/moviecluster_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# CORS Allowed Origins
cors.allowed.origins=http://movie-rating-frontend:3000

# Kafka
spring.kafka.bootstrap-servers=kafka:19092