spring.datasource.url=jdbc:postgresql://postgresql:5432/moviecluster_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Minio
minio.url=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket-name=mc-bucket

# File sizes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# Kafka
spring.kafka.bootstrap-servers=kafka:19092