create table user_profile(  
    id int primary key generated by default as identity ,  
    username varchar(20) not null,  
    password varchar not null,  
    description varchar(500) default '',  
    average_rating numeric(4, 2) not null check (average_rating <= 10.00) default 0,  
    scores int not null default 0,  
    role varchar not null default 'USER'  
);

create table movie(  
    id int primary key generated by default as identity ,  
    title varchar(50) not null ,  
    release_year int check (release_year > 0),  
    description varchar(500) not null default '',  
    average_rating numeric(4, 2) not null check (average_rating <= 10.00)  
        default 0,  
    scores int not null default 0  
);

create table rating(  
    rating_id int primary key generated by default as identity ,  
    user_id int not null,  
    movie_id int not null,  
    rating int not null check (rating >= 1 and rating <= 10),  
    date timestamp not null  
);

create table file (
    id int primary key generated by default as identity ,
    url text,
    uploaded_at timestamp
);