create table user_profile(  
    id bigint primary key generated by default as identity ,
    username varchar(20) not null,  
    password varchar not null,  
    description varchar(500) default '',  
    average_rating numeric(4, 2) not null check (average_rating <= 10.00) default 0,  
    scores int not null default 0,  
    role varchar not null default 'USER'  
);

create table movie(  
    id bigint primary key generated by default as identity ,
    title varchar(50) not null ,  
    release_year int check (release_year > 0),  
    description varchar(500) not null default '',  
    average_rating numeric(4, 2) not null check (average_rating <= 10.00)  
        default 0,  
    scores int not null default 0,
    created_at timestamp with time zone default current_timestamp
);

create table rating(  
    rating_id bigint primary key generated by default as identity ,
    user_id bigint not null,
    movie_id bigint not null,
    rating int not null check (rating >= 1 and rating <= 10),  
    ratedAt timestamp not null
);

create table file (
    id bigint primary key generated by default as identity ,
    url text,
    uploaded_at timestamp
);

create table file_attachment (
    id bigint primary key generated by default as identity ,
    file_id bigint unique references file(id) not null ,
    entity_type varchar(50) not null,
    entity_id bigint not null,
    uploaded_at timestamp not null
);

create table refresh_token (
    id bigint primary key generated by default as identity ,
    user_id bigint not null,
    refresh_token varchar not null,
    unique (user_id, refresh_token)
);