spring.application.name=feed-service

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.contexts=dev
spring.liquibase.default-schema=public

# Secret key
auth.jwt.secret=moviecluster

# Kafka
spring.kafka.post-created-topic.name=post-created

# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=user-profile