spring.datasource.url=jdbc:postgresql://localhost:5432/moviecluster_db
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8086

# PostgreSQL
spring.jpa.properties.hibernate.show_sql=true

# User Profile Service URL
user-profile-service.url=http://localhost:8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092