spring.application.name=feed-service

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.contexts=dev
spring.liquibase.default-schema=public

# Secret key
auth.jwt.secret=moviecluster

# Kafka
spring.kafka.post-created-topic.name=post-created