spring.profiles.active=dev

spring.application.name=movie-catalog

# PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.contexts=dev
spring.liquibase.default-schema=public

# ElasticSearch
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.index.movies=movies

# Secret key
auth.jwt.secret=moviecluster

# Kafka
spring.kafka.movie-updated-topic.name=movies-updated
spring.kafka.movie-rating-updated-topic.name=movies-rating-updated
spring.kafka.movie-deleted-topic.name=movies-deleted

# Redis
spring.cache.type=redis

# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=movie-catalog
