# ElasticSearch
spring.elasticsearch.uris=http://esearch-storage:9200

# Secret key
auth.jwt.secret=moviecluster

# Kafka
spring.kafka.bootstrap-servers=kafka:19092

# Movie Catalog Service URL
movie-catalog.service.url=http://movie-catalog:8081