server.port=8084

# CORS Allowed Origins
cors.allowed.origins=http://localhost:3000

# ElasticSearch
spring.elasticsearch.uris=localhost:9200

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Movie Catalog Service URL
movie-catalog.service.url=http://localhost:8081