# ElasticSearch
spring.elasticsearch.uris=http://esearch-storage:9200

# CORS Allowed Origins
cors.allowed.origins=http://movie-rating-frontend:3000

# Kafka
spring.kafka.bootstrap-servers=kafka:19092

# Movie Catalog Service URL
movie-catalog.service.url=http://movie-catalog:8080