spring.profiles.active=dev

spring.application.name=user-library

# ElasticSearch
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s
spring.elasticsearch.index.user-rated-movies=user-rated-movies

# Secret key
auth.jwt.secret=moviecluster

# Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=rating-system